### ISSUE TITLE
Update vendored `subset_network.R` file

### ISSUE THREAD

**Issue by aaraney** [lynker-spatial/hfsubsetCLI#21]
Related to #20, the vendored version of `subset_network.R` is now out of sync. The appears to be causing several issues (see #20; corrupted layer crs). It appears both of these issues have been addressed in the latest version of `subset_network.R`. See:
https://github.com/NOAA-OWP/hydrofabric/blob/b07c1097608cca386cb29085e0976eabfc91d42c/R/subset_network.R

**Comment by aaraney** [comment]
We may want to consider creating a github action that opens a PR when the vendored version changes.

**Comment by aaraney** [comment]
I looks like `runtime.R` will need to be slightly tweaks after updating.

**Comment by program--** [comment]
Closing since this does not apply to the new v1.0.0 release anymore
